import type { AnchorFragment } from '@/lib/types';

export const ANCHOR_FRAGMENTS: AnchorFragment[] = [
  {
    id: "inn_basement_future",
    phase: "act1",
    trigger: "玩家读过林深第一封信，或再次提到客栈",
    clue: "王掌柜随口说客栈下面只有压酒瓮的土窖，去年还塌过一角；这和林深说的'地下多了一层'不完全一致。",
    eventCode: "anchor_inn_basement_future",
  },
  {
    id: "letter_without_postroad",
    phase: "act1",
    trigger: "李无名第一次或第二次登场",
    clue: "李无名看一眼玩家袖口，低声说：有些信不是从驿路来的，拆开前要先问自己愿不愿意被看见。",
    eventCode: "anchor_letter_without_postroad",
  },
  {
    id: "missing_ward_map",
    phase: "act1",
    trigger: "玩家问路、看坊图或经过坊门",
    clue: "坊图上有一小块被新墨盖住，旁边老吏说这坊名从来没改过，但墨下隐约不是同一个字。",
    eventCode: "anchor_missing_ward_map",
  },
  {
    id: "persian_song_future_echo",
    phase: "act1",
    roles: ["musician", "wanderer"],
    trigger: "阿依或酒肆乐声出现",
    clue: "阿依哼出一小段旋律，说是母亲教的；旋律却像林深信里提过的2077广告铃声。",
    eventCode: "anchor_persian_song_future_echo",
  },
  {
    id: "ledger_price_drift",
    phase: "act1",
    roles: ["merchant", "scholar"],
    trigger: "玩家接触账本、货价或西市交易",
    clue: "同一批胡椒在两本账上价格差了三倍，王掌柜说是边地消息闹的，随即又把话咽回去。",
    eventCode: "anchor_ledger_price_drift",
  },
  {
    id: "guard_knows_name",
    phase: "act1",
    trigger: "玩家再次经过城门或被守卫盘问",
    clue: "守门兵叫出了玩家没有报过的姓氏，随后又像自己也困惑，改口说认错人。",
    eventCode: "anchor_guard_knows_name",
  },
  {
    id: "ceramic_warm_after_letter",
    phase: "act1",
    trigger: "玩家读信后靠近或忽视邮箱",
    clue: "唐三彩陶器没有发光，却像刚被人从袖中捂热，釉面里有一瞬映出不是长安的白色灯管。",
    eventCode: "anchor_ceramic_warm_after_letter",
  },
  {
    id: "linshen_wrong_tree",
    phase: "act2",
    trigger: "林深提到客栈外景，或玩家调查客栈外",
    clue: "林深说客栈对面有一棵枣树；王掌柜却说那里三年前就是面摊，从未种树。",
    eventCode: "anchor_linshen_wrong_tree",
  },
  {
    id: "future_food_smell",
    phase: "act2",
    trigger: "玩家吃饭、闻到食物或进入酒肆",
    clue: "热汤里有一瞬出现近似合成食物的金属甜味，只有玩家注意到，旁人都说只是胡椒放多了。",
    eventCode: "anchor_future_food_smell",
  },
  {
    id: "ai_scribe_copy",
    phase: "act2",
    roles: ["scholar"],
    trigger: "玩家接触书坊、抄书人或策论",
    clue: "一个抄书童写出的字和玩家怀中策论某一页完全相同，连墨污位置都一致。",
    eventCode: "anchor_ai_scribe_copy",
  },
  {
    id: "blade_notch_memory",
    phase: "act2",
    roles: ["wanderer"],
    trigger: "玩家拔刀、遇到争执或检查兵器",
    clue: "短刀上新出现一道缺口，像刚格开过什么；玩家却不记得这一击发生过。",
    eventCode: "anchor_blade_notch_memory",
  },
  {
    id: "market_fire_not_yet",
    phase: "act2",
    trigger: "西市傍晚、人群骚动或火光出现",
    clue: "有人喊西市失火，但赶到时只有湿灰；一个孩童说火是'明天烧的'。",
    eventCode: "anchor_market_fire_not_yet",
  },
  {
    id: "border_report_whisper",
    phase: "act3",
    trigger: "官差、驿卒、军报或第三幕任意街景",
    clue: "驿卒怀里的军报只露出'范阳'二字，酒客立刻压低声音，不肯再谈。",
    eventCode: "anchor_border_report_whisper",
  },
  {
    id: "leaving_changan_cart",
    phase: "act3",
    trigger: "玩家经过坊门、客栈门口或清晨街道",
    clue: "一户富人家天未亮就装车离京，仆人说只是探亲，箱笼却像再也不回。",
    eventCode: "anchor_leaving_changan_cart",
  },
  {
    id: "linshen_knows_end",
    phase: "act3",
    trigger: "林深来信或玩家追问长安未来",
    clue: "林深写到'别太习惯长安现在的声音'，又把后半句划掉，纸面上有反复停笔的痕迹。",
    eventCode: "anchor_linshen_knows_end",
  },
  {
    id: "second_correspondent_shadow",
    phase: "act3",
    trigger: "玩家已有多封通信后查看信匣或回信",
    clue: "信匣底部夹着一小片不属于玩家的纸角，只写着'那位书生也收到了吗'。",
    eventCode: "anchor_second_correspondent_shadow",
  },
];
